Repository HanHwa-Team1-Final-Project/MOIM-BE, pull requests merged in 2024-04, with the labels that each got.

#53 [Fix] 도커 이미지 이슈 해결
  .dockerignore
  Dockerfile
  docker-compose.yml
  src/main/java/com/team1/moim/global/config/sse/service/SseService.java
Labels: 백엔드-개발

#56 [Feat] 호스트가 모임 참여자 리스트에 추가되었을 때 Exception 발생
  src/main/java/com/team1/moim/domain/group/exception/HostIncludedException.java
  src/main/java/com/team1/moim/domain/group/service/GroupService.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 백엔드-개발

#57 코드 정리
  src/main/java/com/team1/moim/domain/event/entity/Alarm.java
  src/main/java/com/team1/moim/domain/event/entity/Event.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/global/config/sse/repository/EmitterRepository.java
  src/main/java/com/team1/moim/global/config/sse/service/SseService.java
Labels: 백엔드-개발

#59 [Refactor] 모임 생성 코드 리팩토링
  src/main/java/com/team1/moim/domain/group/controller/GroupController.java
  src/main/java/com/team1/moim/domain/group/dto/request/GroupAlarmRequest.java
  src/main/java/com/team1/moim/domain/group/dto/response/VoteResponse.java
  src/main/java/com/team1/moim/domain/group/entity/Group.java
  src/main/java/com/team1/moim/domain/group/entity/GroupAlarm.java
  src/main/java/com/team1/moim/domain/group/entity/GroupAlarmType.java
  src/main/java/com/team1/moim/domain/group/entity/GroupInfo.java
  src/main/java/com/team1/moim/domain/group/exception/GroupAndGroupInfoNotMatchException.java
  src/main/java/com/team1/moim/domain/group/repository/GroupAlarmRepository.java
  src/main/java/com/team1/moim/domain/group/service/GroupService.java
  src/main/java/com/team1/moim/domain/notification/controller/NotificationController.java
  src/main/java/com/team1/moim/domain/notification/service/NotificationService.java
  src/main/java/com/team1/moim/global/config/sse/dto/GroupNotificationScheduler.java
  src/main/java/com/team1/moim/global/config/sse/dto/MessageCreator.java
  src/main/java/com/team1/moim/global/config/sse/service/SseService.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 버그, 기타, 백엔드-개발

#60 Update README.md
  README.md
Labels: 기타

#62 [Fix] URI 수정
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/group/controller/GroupController.java
Labels: 기타, 백엔드-개발

#63 Add files via upload
  assets/test/events/1-1.eventCreate_basic(result).png
  assets/test/events/1.eventCreate_basic(request).png
  assets/test/events/2-1.eventCreate_alarm(result).png
  assets/test/events/2-2.eventCreate_alarm(db).png
  assets/test/events/2.eventCreate_alarm(request).png
  assets/test/events/3-1.eventCreate_repeat(result).png
  assets/test/events/3-2.eventCreate_repeat(db).png
  assets/test/events/3.eventCreate_repeat(request).png
  assets/test/events/4-1.eventCreate_todo(result).png
  assets/test/events/4-2eventCreate_todo(db).png
  assets/test/events/4.eventCreate_todo(request).png
  assets/test/events/5-1.eventUpdate(result).png
  assets/test/events/5.eventUpdate(request).png
  assets/test/events/6.eventDelete.png
  assets/test/events/7.eventSse.png
Labels: 기타

#64 Add files via upload
  assets/test/groups/get_confirmed_group(failed).png
  assets/test/groups/get_confirmed_group.png
  assets/test/groups/get_pending_group(failed).png
  assets/test/groups/get_pending_group.png
  assets/test/groups/group_create(request).png
  assets/test/groups/group_create(response).png
  assets/test/groups/group_delete(failed).png
  assets/test/groups/group_delete.png
Labels: 기타

#65 Add files via upload
  assets/test/members/find my info.png
  assets/test/members/member delete.png
  assets/test/members/member login.png
  assets/test/members/member sign up.png
Labels: 기타

#70 [Refactor/Auth] 이메일 인증 관련 코드 리팩토링, 회원가입 시 필요한 기능 추가
  src/main/java/com/team1/moim/domain/auth/controller/AuthController.java
  src/main/java/com/team1/moim/domain/auth/exception/CodeNotMatchException.java
  src/main/java/com/team1/moim/domain/auth/exception/NotFoundCodeException.java
  src/main/java/com/team1/moim/domain/auth/service/AuthService.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 버그, 백엔드-개발

#69 [Feat/Event]메트릭스 이벤트 조회 api 추가
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
Labels: 백엔드-개발

#71 [Fix/Auth] Axios 로그인 요청 시 CORS 에러 이슈 해결
  src/main/java/com/team1/moim/global/config/security/SecurityConfig.java
  src/main/java/com/team1/moim/global/config/security/WebConfig.java
Labels: 버그

#66 [Feat] 알림 redis 저장
  src/main/java/com/team1/moim/domain/auth/service/AuthService.java
  src/main/java/com/team1/moim/domain/event/dto/response/AlarmResponse.java
  src/main/java/com/team1/moim/domain/event/dto/response/EventResponse.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/domain/notification/controller/NotificationController.java
  src/main/java/com/team1/moim/domain/notification/service/NotificationService.java
  src/main/java/com/team1/moim/global/config/redis/RedisConfig.java
  src/main/java/com/team1/moim/global/config/redis/RedisService.java
  src/main/java/com/team1/moim/global/config/sse/controller/SseController.java
  src/main/java/com/team1/moim/global/config/sse/dto/NotificationResponse.java
  src/main/java/com/team1/moim/global/config/sse/service/SseService.java
Labels: 백엔드-개발

#74 모임 알림 저장 및 알림 공통 조회
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/domain/group/controller/GroupController.java
  src/main/java/com/team1/moim/domain/group/service/GroupService.java
  src/main/java/com/team1/moim/domain/notification/NotificationType.java
  src/main/java/com/team1/moim/domain/notification/controller/NotificationController.java
  src/main/java/com/team1/moim/domain/notification/dto/EventNotification.java
  src/main/java/com/team1/moim/domain/notification/dto/GroupNotification.java
  src/main/java/com/team1/moim/domain/notification/dto/NotificationResponseNew.java
  src/main/java/com/team1/moim/domain/notification/service/NotificationService.java
  src/main/java/com/team1/moim/global/config/redis/RedisConfig.java
  src/main/java/com/team1/moim/global/config/redis/RedisService.java
  src/main/java/com/team1/moim/global/config/sse/NotificationType.java
  src/main/java/com/team1/moim/global/config/sse/dto/GroupNotification.java
  src/main/java/com/team1/moim/global/config/sse/service/SseService.java
Labels: 백엔드-개발

#76 Eunji/event 일정 검색기능 추가, 메트릭스 일정 오름차순 정렬
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/repository/EventRepository.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/domain/event/service/PublicHoliyDayAPI.java
Labels: 백엔드-개발

#77 [Fix/login] 로그인 관련 코드 수정
  src/main/java/com/team1/moim/domain/auth/controller/AuthController.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtProvider.java
  src/main/resources/static/index.html
Labels: 버그, 백엔드-개발

#81 [Refactor/events] 일정 관련 코드 리팩토링
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/dto/request/AlarmRequest.java
  src/main/java/com/team1/moim/domain/event/dto/request/EventRequest.java
  src/main/java/com/team1/moim/domain/event/dto/request/RepeatRequest.java
  src/main/java/com/team1/moim/domain/event/dto/request/ToDoListRequest.java
  src/main/java/com/team1/moim/domain/event/entity/Alarm.java
  src/main/java/com/team1/moim/domain/event/entity/Event.java
  src/main/java/com/team1/moim/domain/event/entity/Repeat.java
  src/main/java/com/team1/moim/domain/event/entity/ToDoList.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/domain/member/entity/Member.java
Labels: 기타, 백엔드-개발

#82 [Fix] 월별 조회 쿼리 수정
  src/main/java/com/team1/moim/domain/event/repository/EventRepository.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
Labels: 백엔드-개발

#87 [Feat/Event] 단일 일정의 알림 조회 기능 추가 및 글자 수 이슈 해결
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/entity/Event.java
  src/main/java/com/team1/moim/domain/event/exception/AlarmNotFoundException.java
  src/main/java/com/team1/moim/domain/event/repository/AlarmRepository.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/domain/group/entity/Group.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 백엔드-개발

#94 [Feat] 업로드된 파일 수정
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
Labels: 버그

#93 [Fix/Login] 만료된 Access Token 재발급 안되는 이슈 해결(#92)
  src/main/java/com/team1/moim/global/config/security/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtProvider.java
  src/main/java/com/team1/moim/global/config/security/jwt/exception/RefreshTokenNotFoundException.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 버그, 백엔드-개발

#99 [Fix] 아이젠하워 매트릭스 조회 관련 수정
  src/main/java/com/team1/moim/domain/event/repository/EventRepository.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
Labels: 버그, 백엔드-개발

#103 [Fix] 국경일 정보 조회하지 못하는 문제 수정
  src/main/java/com/team1/moim/domain/event/controller/EventController.java
  src/main/java/com/team1/moim/domain/event/service/PublicHoliyDayAPI.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtAuthenticationProcessingFilter.java
Labels: 버그

#114 [Feat/oauth] 구글, 카카오 로그인 백엔드에 연결
  src/main/java/com/team1/moim/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/team1/moim/domain/auth/service/AuthService.java
  src/main/java/com/team1/moim/domain/member/controller/MemberController.java
  src/main/java/com/team1/moim/domain/member/entity/Account.java
  src/main/java/com/team1/moim/domain/member/entity/LoginType.java
  src/main/java/com/team1/moim/domain/member/entity/Member.java
  src/main/java/com/team1/moim/domain/member/entity/Role.java
  src/main/java/com/team1/moim/domain/member/entity/SocialType.java
  src/main/java/com/team1/moim/domain/member/exception/AccountNotFoundException.java
  src/main/java/com/team1/moim/domain/member/repository/AccountRepository.java
  src/main/java/com/team1/moim/domain/member/repository/MemberRepository.java
  src/main/java/com/team1/moim/domain/member/service/MemberService.java
  src/main/java/com/team1/moim/global/config/security/PasswordUtil.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtProvider.java
  src/main/java/com/team1/moim/global/config/security/login/handler/LoginSuccessHandler.java
  src/main/java/com/team1/moim/global/config/security/login/service/LoginService.java
  src/main/java/com/team1/moim/global/config/security/oauth2/CustomOAuth2User.java
  src/main/java/com/team1/moim/global/config/security/oauth2/OAuthAttributes.java
  src/main/java/com/team1/moim/global/config/security/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/team1/moim/global/config/security/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/team1/moim/global/config/security/oauth2/userinfo/GoogleOAuth2UserInfo.java
  src/main/java/com/team1/moim/global/config/security/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/com/team1/moim/global/config/security/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 버그, 백엔드-개발

#117 [Fix/Login] 일반 로그인 에러 해결(#116)
  src/main/java/com/team1/moim/global/config/security/SecurityConfig.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtAuthenticationProcessingFilter.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtProvider.java
  src/main/java/com/team1/moim/global/config/security/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/team1/moim/global/config/security/login/handler/LoginSuccessHandler.java
  src/main/java/com/team1/moim/global/config/security/login/service/LoginService.java
Labels: 버그

#119 [Feat] 채팅 기능 개발
  build.gradle
  src/main/java/com/team1/moim/domain/chat/config/StompExceptionHandler.java
  src/main/java/com/team1/moim/domain/chat/config/StompHandler.java
  src/main/java/com/team1/moim/domain/chat/config/WebSocketConfig.java
  src/main/java/com/team1/moim/domain/chat/controller/ChatController.java
  src/main/java/com/team1/moim/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/team1/moim/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/team1/moim/domain/chat/entity/Chat.java
  src/main/java/com/team1/moim/domain/chat/entity/MemberRoom.java
  src/main/java/com/team1/moim/domain/chat/entity/MessageType.java
  src/main/java/com/team1/moim/domain/chat/entity/Room.java
  src/main/java/com/team1/moim/domain/chat/repository/ChatRepository.java
  src/main/java/com/team1/moim/domain/chat/repository/RoomRepository.java
  src/main/java/com/team1/moim/domain/chat/service/ChatService.java
  src/main/java/com/team1/moim/domain/event/service/EventService.java
  src/main/java/com/team1/moim/domain/group/dto/response/VoteResponse.java
  src/main/java/com/team1/moim/domain/notification/dto/NotificationResponseNew.java
  src/main/java/com/team1/moim/global/config/security/jwt/JwtProvider.java
  src/main/java/com/team1/moim/global/config/security/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/com/team1/moim/global/exception/UnauthorizedException.java
Labels: 백엔드-개발

#123 Jaeseok/chat room
  src/main/java/com/team1/moim/domain/chat/controller/RoomController.java
  src/main/java/com/team1/moim/domain/chat/dto/request/MemberRoomRequest.java
  src/main/java/com/team1/moim/domain/chat/dto/request/RoomRequest.java
  src/main/java/com/team1/moim/domain/chat/dto/response/RoomDetailResponse.java
  src/main/java/com/team1/moim/domain/chat/entity/MemberRoom.java
  src/main/java/com/team1/moim/domain/chat/entity/Room.java
  src/main/java/com/team1/moim/domain/chat/exception/HostChatIncludedException.java
  src/main/java/com/team1/moim/domain/chat/exception/NoChatParticipantsException.java
  src/main/java/com/team1/moim/domain/chat/repository/MemberRoomRepository.java
  src/main/java/com/team1/moim/domain/chat/service/RoomService.java
  src/main/java/com/team1/moim/domain/group/controller/GroupController.java
  src/main/java/com/team1/moim/domain/notification/service/NotificationService.java
  src/main/java/com/team1/moim/global/exception/ErrorCode.java
Labels: 백엔드-개발
